import { test } from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { loadSiteData, loadContext } from '../tools/load-data.mjs';
import { generate } from '../bench/to-site.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fixture = path.join(root, 'tests', 'fixtures', 'results');
const cli = path.join(root, 'bench', 'to-site.mjs');

// Site root for the loaders: the real registry, compare data and engines, plus freshly generated data/bench.
function siteRoot() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'to-site-'));
  fs.cpSync(path.join(root, 'data'), path.join(tmp, 'data'), { recursive: true });
  fs.rmSync(path.join(tmp, 'data', 'bench'), { recursive: true, force: true });
  generate(fixture, path.join(tmp, 'data', 'bench'));
  return tmp;
}

const site = siteRoot();
const RT = loadSiteData(site);
const llama = RT.bench['llama-cpp'];
const vllm = RT.bench.vllm;

test('fixture tree gives the expected medians for level 1', () => {
  const l = llama.levels[0];
  assert.equal(l.users, 1);
  assert.deepEqual(l.ttft_ms, { median: 25, min: 20, max: 30 });
  assert.deepEqual(l.tok_s, { median: 105, min: 100, max: 110 });
  assert.deepEqual(l.itl_ms, { median: 11, min: 10, max: 12 });
  assert.deepEqual(l.e2e_ms, { median: 1050, min: 1000, max: 1100 });
  assert.deepEqual(l.prefill_ms, { median: 16, min: 15, max: 17 });
  assert.equal(l.queue_ms, undefined);
  const v = vllm.levels[0];
  assert.deepEqual(v.ttft_ms, { median: 12, min: 10, max: 14 });
  assert.deepEqual(v.prefill_ms, { median: 9, min: 8, max: 10 });
  assert.deepEqual(v.queue_ms, { median: 2, min: 1, max: 3 });
});

test('a valid:false level is absent for that engine and present for the other', () => {
  assert.deepEqual(llama.levels.map(l => l.users), [1]);
  assert.deepEqual(vllm.levels.map(l => l.users), [1, 2]);
});

test('a repeat with a server error object is skipped for server fields only', () => {
  const l2 = vllm.levels[1];
  assert.deepEqual(l2.prefill_ms, { median: 12, min: 12, max: 12 });
  assert.deepEqual(l2.ttft_ms, { median: 17, min: 16, max: 18 });
});

test('run block, reuse and kvFull', () => {
  assert.deepEqual(llama.run, { date: '2026-10-06', gpu: 'Test GPU 24GB', model: 'Llama 3.1 8B Instruct', commit: 'aaaaaaa', config: 'main' });
  assert.equal(vllm.run.commit, 'bbbbbbb');
  assert.equal(llama.id, 'llama-cpp');
  assert.deepEqual(llama.reuse, { cold_ttft_ms: 1200, warm_ttft_ms: 90, warm_cache_n_median: 480 });
  assert.deepEqual(vllm.reuse, { cold_ttft_ms: 1100, warm_ttft_ms: 40 });
  assert.deepEqual(llama.kvFull, [
    { max_tokens: 256, tok_s: 490, ttft_ms: 210, kv_retries: 0, failed: 0 },
    { max_tokens: 1024, tok_s: 305, ttft_ms: 925, kv_retries: 7, failed: 2 },
  ]);
  assert.deepEqual(vllm.kvFull[1], { max_tokens: 1024, tok_s: 2150, ttft_ms: 310, preemptions: 12, failed: 0 });
});

test('generated files load via loadSiteData with no registry errors', () => {
  assert.deepEqual(RT.errors, []);
  assert.ok(RT.bench['llama-cpp']);
  assert.ok(RT.bench.vllm);
});

test('output is deterministic and starts with a generated-by comment', () => {
  const a = fs.mkdtempSync(path.join(os.tmpdir(), 'ts-a-'));
  const b = fs.mkdtempSync(path.join(os.tmpdir(), 'ts-b-'));
  generate(fixture, a);
  generate(fixture, b);
  for (const f of ['llama-cpp.js', 'vllm.js']) {
    const text = fs.readFileSync(path.join(a, f), 'utf8');
    assert.equal(text, fs.readFileSync(path.join(b, f), 'utf8'));
    assert.match(text.split('\n')[0], /^\/\/ Generated by bench\/to-site\.mjs from bench\/results\/results/);
  }
});

test('the generated data renders: q1 evidence is no longer the empty state', () => {
  const extra = ['util.js', 'stage-times.js', 'chart.js', 'render.js'].map(f => path.join(root, 'assets', 'compare', f));
  const c = loadContext(site, extra);
  const q1 = c.RT.compare.questions[0];
  const ctx = { a: c.RT.engines['llama-cpp'], b: c.RT.engines.vllm, pair: null, compare: c.RT.compare, bench: c.RT.bench };
  const html = c.RTR.evidence(q1, ctx);
  assert.doesNotMatch(html, /Benchmark running, results soon/);
  assert.ok(html.length > 200);
});

test('CLI writes both files with --out and fails clearly on an empty folder', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'ts-cli-'));
  const ok = spawnSync(process.execPath, [cli, fixture, '--out', out], { encoding: 'utf8' });
  assert.equal(ok.status, 0, ok.stderr);
  assert.deepEqual(fs.readdirSync(out).sort(), ['llama-cpp.js', 'vllm.js']);
  const empty = fs.mkdtempSync(path.join(os.tmpdir(), 'ts-empty-'));
  fs.writeFileSync(path.join(empty, 'env.json'), JSON.stringify({ date: 'x', gpu: { name: 'g' }, commits: {} }));
  const bad = spawnSync(process.execPath, [cli, empty, '--out', out], { encoding: 'utf8' });
  assert.notEqual(bad.status, 0);
  assert.match(bad.stderr, /no valid main-config summaries/);
});
